DROP DATABASE MARTCODE;
CREATE DATABASE MARTCODE;
USE MARTCODE;

CREATE TABLE PRODUTO (
cod_produto INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
marca VARCHAR(120) NOT NULL
);

CREATE TABLE MERCADO_FORNECEDOR (
cod_mercado_fornecedor INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(120) NOT NULL,
endereco VARCHAR(120) NOT NULL,
contato VARCHAR(120)
);

CREATE TABLE ESTOQUE (
cod_estoque INT AUTO_INCREMENT,
cod_mercado_fornecedor INT,
cod_produto INT,
quantidade INT NOT NULL,
sistema_medida VARCHAR(3) NOT NULL,
validade DATE NOT NULL,
categoria VARCHAR(120) NOT NULL,
PRIMARY KEY(cod_estoque),
FOREIGN KEY(cod_produto) REFERENCES PRODUTO(cod_produto),
FOREIGN KEY(cod_mercado_fornecedor) REFERENCES MERCADO_FORNECEDOR(cod_mercado_fornecedor)
);


